### ISSUE TITLE
关于Unity开发的支持

### ISSUE THREAD

**Issue by warlock07** [RokidGlass/glass2-docs#111]
麻烦发送工程参考到邮箱，关于unity开发调用眼镜侧边按钮左滑、右滑以及返回按键响应的api，就像语音示例工程文件一样，带arr包可以调用的，谢谢，邮箱地址956701603@qq.com

**Comment by XRWorld17** [comment]
邮件已发送，请参考，谢谢

**Comment by 1498308415** [comment]
你好，可以给我也发一份吗，地址1498308415@qq.com，谢谢

**Comment by XRWorld17** [comment]
> 你好，可以给我也发一份吗，地址[1498308415@qq.com](mailto:1498308415@qq.com)，谢谢

if (Application.platform == RuntimePlatform.Android && Input.GetKeyDown(KeyCode.Escape)) // 返回键
        {
            Debug.Log("-UXR- Input KeyCode Escape"); 
        }

        if (Application.platform == RuntimePlatform.Android && (Input.GetButtonDown("Fire1") ) ) //确定键
        {
            Debug.Log("-UXR- Input KEYCODE_DPAD_CENTER");
        }

        if (Application.platform == RuntimePlatform.Android && Input.GetKeyDown(KeyCode.UpArrow)) // KEYCODE_DPAD_UP
        {
            Debug.Log("-UXR- Input  KEYCODE_DPAD_UP");
        }

        if (Application.platform == RuntimePlatform.Android && (Input.GetKeyDown((KeyCode.DownArrow)))) //KEYCODE_DPAD_DOWN
        {
            Debug.Log("-UXR- Input KEYCODE_DPAD_DOWN");
        }

**Comment by 1498308415** [comment]
您好，收到，非常感谢，另外问一下人脸识别有支持unity开发的SDK或者arr包吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RokidGlass/glass2-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RokidGlass/glass2-docs] 关于Unity开发的支持 (#111)





  
***@***.***，谢谢
  
if (Application.platform == RuntimePlatform.Android &amp;&amp; Input.GetKeyDown(KeyCode.Escape)) // 返回键
 {
 Debug.Log("-UXR- Input KeyCode Escape");
 }
     if (Application.platform == RuntimePlatform.Android &amp;&amp; (Input.GetButtonDown("Fire1") ) ) //确定键     {         Debug.Log("-UXR- Input KEYCODE_DPAD_CENTER");     }     if (Application.platform == RuntimePlatform.Android &amp;&amp; Input.GetKeyDown(KeyCode.UpArrow)) // KEYCODE_DPAD_UP     {         Debug.Log("-UXR- Input  KEYCODE_DPAD_UP");     }     if (Application.platform == RuntimePlatform.Android &amp;&amp; (Input.GetKeyDown((KeyCode.DownArrow)))) //KEYCODE_DPAD_DOWN     {         Debug.Log("-UXR- Input KEYCODE_DPAD_DOWN");     }

**Comment by XRWorld17** [comment]
> 您好，收到，非常感谢，另外问一下人脸识别有支持unity开发的SDK或者arr包吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "RokidGlass/glass2-docs" ***@***.***&gt;; 发送时间:&nbsp;2021年3月18日(星期四) 下午3:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [RokidGlass/glass2-docs] 关于Unity开发的支持 (#111) ***@***.***，谢谢 if (Application.platform == RuntimePlatform.Android &amp;&amp; Input.GetKeyDown(KeyCode.Escape)) // 返回键 { Debug.Log("-UXR- Input KeyCode Escape"); } if (Application.platform == RuntimePlatform.Android &amp;&amp; (Input.GetButtonDown("Fire1") ) ) //确定键 { Debug.Log("-UXR- Input KEYCODE_DPAD_CENTER"); } if (Application.platform == RuntimePlatform.Android &amp;&amp; Input.GetKeyDown(KeyCode.UpArrow)) // KEYCODE_DPAD_UP { Debug.Log("-UXR- Input KEYCODE_DPAD_UP"); } if (Application.platform == RuntimePlatform.Android &amp;&amp; (Input.GetKeyDown((KeyCode.DownArrow)))) //KEYCODE_DPAD_DOWN { Debug.Log("-UXR- Input KEYCODE_DPAD_DOWN"); } — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.


您好，人脸识别 unity目前没有

**Comment by 1498308415** [comment]
收到，那关于摄像头的控制有支持unity的方法吗，比如我获得摄像头图像用其他方法进行识别




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RokidGlass/glass2-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RokidGlass/glass2-docs] 关于Unity开发的支持 (#111)





  
您好，收到，非常感谢，另外问一下人脸识别有支持unity开发的SDK或者arr包吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "RokidGlass/glass2-docs" @.&gt;; 发送时间:&nbsp;2021年3月18日(星期四) 下午3:42 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [RokidGlass/glass2-docs] 关于Unity开发的支持 (#111) @.***，谢谢 if (Application.platform == RuntimePlatform.Android &amp;&amp; Input.GetKeyDown(KeyCode.Escape)) // 返回键 { Debug.Log("-UXR- Input KeyCode Escape"); } if (Application.platform == RuntimePlatform.Android &amp;&amp; (Input.GetButtonDown("Fire1") ) ) //确定键 { Debug.Log("-UXR- Input KEYCODE_DPAD_CENTER"); } if (Application.platform == RuntimePlatform.Android &amp;&amp; Input.GetKeyDown(KeyCode.UpArrow)) // KEYCODE_DPAD_UP { Debug.Log("-UXR- Input KEYCODE_DPAD_UP"); } if (Application.platform == RuntimePlatform.Android &amp;&amp; (Input.GetKeyDown((KeyCode.DownArrow)))) //KEYCODE_DPAD_DOWN { Debug.Log("-UXR- Input KEYCODE_DPAD_DOWN"); } — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您好，人脸识别 unity目前没有

**Comment by XRWorld17** [comment]
> 收到，那关于摄像头的控制有支持unity的方法吗，比如我获得摄像头图像用其他方法进行识别

一种尝试是Unity Android C#中通过WebCamTexture获取，图像格式比较受限
WebCamDevice[] devices = WebCamTexture.devices

**Comment by Hooooyu** [comment]
你好，可以发一份Unity的示例工程到hooyu@vicfun.cn吗 @XRWorld17

**Comment by XRWorld17** [comment]
> 你好，可以发一份Unity的示例工程到[hooyu@vicfun.cn](mailto:hooyu@vicfun.cn)吗 @XRWorld17

哪个功能的示例？

**Comment by Hooooyu** [comment]
例如原生的Unity SDK的示例有吗？还是目前来说没有Unity的SDK？

**Comment by XRWorld17** [comment]
> 例如原生的Unity SDK的示例有吗？还是目前来说没有Unity的SDK？

二代眼镜目前有按键事件、离线语音指令的Unity SDK示例。如需请提供Github账号以加入项目

**Comment by donghe329** [comment]
> @XRWorld17 您好，麻烦发一份unitySDK到dh.alex@qq.com

**Comment by XRWorld17** [comment]
> > @XRWorld17 您好，麻烦发一份unitySDK到[dh.alex@qq.com](mailto:dh.alex@qq.com)

二代眼镜目前有按键事件、离线语音指令的Unity SDK示例。如需请提供Github账号以加入项目
